package uk.ac.soton.comp1206.event;

import uk.ac.soton.comp1206.game.GamePiece;

/**
 * This interface is used to listen for the next game piece that's generated by
 * the game. This is used to update the UI to display the next piece and the following piece.
 */
public interface NextPieceListener {

    /**
     * handle when a next piece event. Used to update the UI.
     * @param nextpiece the game piece object of the current piece that's about to be played.
     * @param followingPiece the game piece object of the following piece that will be played.
     */
    void nextPiece(GamePiece nextpiece, GamePiece followingPiece);
}
